### ISSUE TITLE
00 -- This is Heavy -- Ben Gohlke

### ISSUE THREAD

**Issue by jcgohlke** [TheIronYard--Orlando/2015--SUMMER--iOS#1]
### Tasks:

* [X] [Create a Github account](https://github.com/signup)
* [X] Find and star [the class project](https://github.com/TheIronYard--Orlando/2015--SUMMER--iOS)
* [ ] Read [the Home page on the class wiki](https://github.com/TheIronYard--Orlando/2015--SUMMER--iOS/wiki)
* [ ] [Create a new _WIP Issue_](https://github.com/TheIronYard--Orlando/2015--SUMMER--iOS/issues/new)
  * [ ] Named `00 -- This is Heavy -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  * [ ] With this checklist as the description
* [ ] [Edit your Github profile](https://github.com/settings/profile) to provide:
  * [ ] A picture, so I can recognize your face.
  * [ ] Your full name, so I can recognize your name.
  * [ ] A valid public email address, so I can contact you if I need to.
* [ ] [Complete the "Hello World" Github guide](https://guides.github.com/activities/hello-world/)
  * [ ] Add a link to your new Github repo as a comment on your *WIP Issue*
* [ ] Create a new repository called `TIY-Assignments`
  * [ ] Check the box to create an initial `README.md` file
  * [ ] Select the `CC0` -- "Creative Commons" license for your work
  * [ ] Add a link to your `TIY-Assignments` repo as a comment on your *WIP Issue*
* [ ] [Complete the "Forking Projects" Github guide](https://guides.github.com/activities/forking/)
    * [ ] Add a link to your `Fork-and-Spoon` repo as a comment on your *WIP Issue*
* [ ] Install Xcode from the Mac App Store. Simply search for _Xcode_.
* [ ] Open Xcode. Click the _Xcode_ menu in the menubar, then choose _Preferences_. Navigate to the _Downloads_ tab and install the latest iOS documentation (currently iOS 8.3). Once fully downloaded, the docset should have a small checkmark next to it.
* [ ] Install Dash from the Mac App Store. Navigate to the Dash app's preferences and choose the _Downloads_ tab. Install the following docsets:
    * [ ] iOS 8.3 (or latest, it will find the already loaded set from the step above)
    * [ ] Swift 1.2 (or latest)
    * [ ] Objective-C
    * [ ] Objective-C Blocks
    * [ ] Xcode
    * [ ] iOS Design
    * [ ] Take a screenshot of the _Docsets_ tab in preferences and attach it to your _WIP Issue_
* [ ] Watch _The Long Run_ Videos on [Delve.tv](http://delve.tv)
   * [ ] [_The Long Game_, part 1](http://delve.tv/the-long-game-part-one/)
   * [ ] [_The Long Game_, part 2](http://delve.tv/the-long-game-part-2/)

### Deliverables:

* [x] _WIP Issue_
  * [x] named `00 -- This is Heavy -- YOUR NAME`
  * [x] with description matching __Tasks__
* [x] A Github Profile with:
  * [x] Intelligible picture of yourself
  * [x] Your full name
  * [x] A valid email address
* [ ] Comments on your *WIP Issue* with links to your repos for
  * [ ] `Hello-World`
  * [ ] `TIY-Assignments`
  * [ ] `Fork-and-Spoon`
  * [ ] Attached image from the Dash preference pane for installed docsets

**Comment by DevInnovator** [comment]
I can't get Counter.xcodeproj to open automatically in Xcode when I click the link in Github. Please advise.

**Comment by jholsapple** [comment]
I'm having the same issue. Is this a test??

**Comment by KevinSFC** [comment]
Use the "Clone in Desktop" option guys:
![screen shot 2015-06-09 at 1 56 16 am](https://cloud.githubusercontent.com/assets/6679175/8051481/cecaac0c-0e4a-11e5-91b1-c09576875e1c.png)

**Comment by jholsapple** [comment]
Thanks Kevin. I was prepared to copy and paste.

**Comment by KevinSFC** [comment]
That would be no fun! :-) Also, get the GitHub Mac App: 

https://mac.github.com

**Comment by jholsapple** [comment]
I'm having some issues with getting the completed app added to TIY-assignments repo. Any suggestions?

**Comment by KevinSFC** [comment]
Did you install the GitHub Macintosh app? When you clone to desktop, it starts to track all your changes and you can open the GitHub App to see the changes you need to commit. 

We should be able to mimic the steps from the "Hello World" & "Forking Projects" GitHub guide, but this will be going to our own individual assignment repos instead - not back to the master repo to be merged.

I am assuming that we are suppose to create a branch and commit the changes we have made to our assignment repos.

**Comment by jholsapple** [comment]
Yeah, I Installed the app. I haven't played with it enough to know my way around. I don't want to mimic the others because it needs to be on TIY repo. 

I'll play with it and get it knocked out. Thanks for the info

**Comment by KevinSFC** [comment]
Yeah, that is what I am looking at right now on Stack Overflow.

**Comment by EliCorrea** [comment]
not able to click the checklist after creating a WIP issue. Please advice. Not sure if i'm doing this correctly.
