### ISSUE TITLE
01 -- Mission Briefing -- Kevin C. Bell

### ISSUE THREAD

**Issue by KevinSFC** [TheIronYard--Orlando/2015--SUMMER--iOS#13]
#### Storyboard Tasks

* [x] The button should really say "Authenticate"
* [x] The textfield should have placeholder text that says "Agent name"
* [x] Each UI element will need to be connected to its associated property in the ViewController class.
* [x] The agent name textfield should capitalize each word typed into it (see the attributes inspector)
* [x] Neither textfield should attempt any autocorrect or spellcheck (again, see attributes inspector)
* [x] The password textfield should hide the characters typed in (it will show dots, see the attributes inspector, see a pattern here?)
* [x] You will notice The Iron Yard logo image is left aligned, and in fact when you click on it, the outline appears orange. It really should be centered in the view like everything else (needs an autolayout constraint).

#### Code Changes

* [x] The UI elements should be set to an "empty string" in viewDidLoad of the ViewController class (#1 in comments).
* [x] The code should check to ensure BOTH the agent name and password fields are nonempty before allowing authentication (#2 in comments).
* [x] The greeting label should display "Good evening, Agent [last name]", where the agent's last name is pulled from the textfield (#3 in comments).
* [x] The mission briefing should display the information from MissionBriefing.txt (copy-paste, you don't have to read from the file). It also contains a placeholder for the agent's last name (#4 in comments).
* [x] The background color of the view should change to green on successful authentication of the agent (#5 in comments).
* [x] The background color of the view should change to red to indicate a failed login of the agent (#6 in comments).

**Comment by jcgohlke** [comment]
Good job. Please review and close this issue.

**Comment by KevinSFC** [comment]
Reviewed.

**Comment by KevinSFC** [comment]
Closed
