### ISSUE TITLE
00 -- This is Heavy -- John Holsapple

### ISSUE THREAD

**Issue by jholsapple** [TheIronYard--Orlando/2015--SUMMER--iOS#3]
### Tasks:

* [X] [Create a Github account](https://github.com/signup)
* [X] Find and star [the class project](https://github.com/TheIronYard--Orlando/2015--SUMMER--iOS)
* [x] Read [the Home page on the class wiki](https://github.com/TheIronYard--Orlando/2015--SUMMER--iOS/wiki)
* [x] [Create a new _WIP Issue_](https://github.com/TheIronYard--Orlando/2015--SUMMER--iOS/issues/new)
  * [x] Named `00 -- This is Heavy -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  * [x] With this checklist as the description
* [x] [Edit your Github profile](https://github.com/settings/profile) to provide:
  * [x] A picture, so I can recognize your face.
  * [x] Your full name, so I can recognize your name.
  * [x] A valid public email address, so I can contact you if I need to.
* [x] [Complete the "Hello World" Github guide](https://guides.github.com/activities/hello-world/)
  * [x] Add a link to your new Github repo as a comment on your *WIP Issue*
* [x] Create a new repository called `TIY-Assignments`
  * [x] Check the box to create an initial `README.md` file
  * [x] Select the `CC0` -- "Creative Commons" license for your work
  * [x] Add a link to your `TIY-Assignments` repo as a comment on your *WIP Issue*
* [x] [Complete the "Forking Projects" Github guide](https://guides.github.com/activities/forking/)
    * [x] Add a link to your `Fork-and-Spoon` repo as a comment on your *WIP Issue*
* [x] Install Xcode from the Mac App Store. Simply search for _Xcode_.
* [x] Open Xcode. Click the _Xcode_ menu in the menubar, then choose _Preferences_. Navigate to the _Downloads_ tab and install the latest iOS documentation (currently iOS 8.3). Once fully downloaded, the docset should have a small checkmark next to it.
* [x] Install Dash from the Mac App Store. Navigate to the Dash app's preferences and choose the _Downloads_ tab. Install the following docsets:
    * [x] iOS 8.3 (or latest, it will find the already loaded set from the step above)
    * [x] Swift 1.2 (or latest)
    * [x] Objective-C
    * [x] Objective-C Blocks
    * [x] Xcode
    * [x] iOS Design
    * [x] Take a screenshot of the _Docsets_ tab in preferences and attach it to your _WIP Issue_
* [x] Watch _The Long Run_ Videos on [Delve.tv](http://delve.tv)
   * [x] [_The Long Game_, part 1](http://delve.tv/the-long-game-part-one/)
   * [x] [_The Long Game_, part 2](http://delve.tv/the-long-game-part-2/)
* [x] Look at the Prework-A file for instructions on how to complete the Counter app.

### Deliverables:

* [x] _WIP Issue_
  * [x] named `00 -- This is Heavy -- YOUR NAME`
  * [x] with description matching __Tasks__
* [x] A Github Profile with:
  * [x] Intelligible picture of yourself
  * [x] Your full name
  * [x] A valid email address
* [x] Comments on your *WIP Issue* with links to your repos for
  * [x] `Hello-World`
  * [x] `TIY-Assignments`
  * [x] `Fork-and-Spoon`
  * [x] Attached image from the Dash preference pane for installed docsets
* [x] A completed Counter app project, added to your TIYAssignments repo

**Comment by jholsapple** [comment]
https://github.com/jholsapple/hello-world.git

**Comment by jholsapple** [comment]
https://github.com/jholsapple/TIY-Assignments.git

**Comment by jholsapple** [comment]
https://github.com/jholsapple/Spoon-Knife.git

**Comment by jholsapple** [comment]
![screen shot 2015-06-08 at 9 48 01 pm](https://cloud.githubusercontent.com/assets/10734717/8049099/3927dfe8-0e28-11e5-8512-e3fef1a1a477.png)

**Comment by jcgohlke** [comment]
Great job. Please review and close this issue.
