### ISSUE TITLE
00 -- This is Heavy -- Kevin C. Bell

### ISSUE THREAD

**Issue by KevinSFC** [TheIronYard--Orlando/2015--SUMMER--iOS#4]
### Tasks:

* [X] [Create a Github account](https://github.com/signup)
* [X] Find and star [the class project](https://github.com/TheIronYard--Orlando/2015--SUMMER--iOS)
* [X] Read [the Home page on the class wiki](https://github.com/TheIronYard--Orlando/2015--SUMMER--iOS/wiki)
* [X] [Create a new _WIP Issue_](https://github.com/TheIronYard--Orlando/2015--SUMMER--iOS/issues/new)
  * [X] Named `00 -- This is Heavy -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  * [X] With this checklist as the description
* [X] [Edit your Github profile](https://github.com/settings/profile) to provide:
  * [x] A picture, so I can recognize your face.
  * [X] Your full name, so I can recognize your name.
  * [x] A valid public email address, so I can contact you if I need to.
* [x] [Complete the "Hello World" Github guide](https://guides.github.com/activities/hello-world/)
  * [x] Add a link to your new Github repo as a comment on your *WIP Issue*
* [x] Create a new repository called `TIY-Assignments`
  * [x] Check the box to create an initial `README.md` file
  * [x] Select the `CC0` -- "Creative Commons" license for your work
  * [x] Add a link to your `TIY-Assignments` repo as a comment on your *WIP Issue*
* [x] [Complete the "Forking Projects" Github guide](https://guides.github.com/activities/forking/)
    * [x] Add a link to your `Fork-and-Spoon` repo as a comment on your *WIP Issue*
* [X] Install Xcode from the Mac App Store. Simply search for _Xcode_.
* [X] Open Xcode. Click the _Xcode_ menu in the menubar, then choose _Preferences_. Navigate to the _Downloads_ tab and install the latest iOS documentation (currently iOS 8.3). Once fully downloaded, the docset should have a small checkmark next to it.
* [X] Install Dash from the Mac App Store. Navigate to the Dash app's preferences and choose the _Downloads_ tab. Install the following docsets:
    * [X] iOS 8.3 (or latest, it will find the already loaded set from the step above)
    * [X] Swift 1.2 (or latest)
    * [X] Objective-C
    * [X] Objective-C Blocks
    * [X] Xcode
    * [X] iOS Design
    * [X] Take a screenshot of the _Docsets_ tab in preferences and attach it to your WIP Issue
* [X] Watch _The Long Run_ Videos on [Delve.tv](http://delve.tv)
   * [X] [_The Long Game_, part 1](http://delve.tv/the-long-game-part-one/)
   * [X] [_The Long Game_, part 2](http://delve.tv/the-long-game-part-2/)
* [X] Look at the Prework-A file for instructions on how to complete the Counter app.

### Deliverables:

* [x] _WIP Issue_
  * [x] named `00 -- This is Heavy -- YOUR NAME`
  * [x] with description matching __Tasks__
* [x] A Github Profile with:
  * [x] Intelligible picture of yourself
  * [x] Your full name
  * [x] A valid email address
* [x] Comments on your *WIP Issue* with links to your repos for
  * [x] `Hello-World`
  * [x] `TIY-Assignments`
  * [x] `Fork-and-Spoon`
  * [x] Attached image from the Dash preference pane for installed docsets
* [x] A completed Counter app project, added to your TIYAssignments repo

**Comment by KevinSFC** [comment]
https://github.com/KevinSFC/hello-world

**Comment by KevinSFC** [comment]
https://github.com/KevinSFC/TIY-Assignments.git

**Comment by KevinSFC** [comment]
![f7e47b30-0e46-11e5-9f94-b04085737874](https://cloud.githubusercontent.com/assets/6679175/8068416/ceed2012-0ec1-11e5-9781-33d1c9a1353a.png)

**Comment by KevinSFC** [comment]
https://github.com/KevinSFC/Spoon-Knife.git

**Comment by KevinSFC** [comment]
I thought I would share something I figured out in Xcode:
 
1. Fork the assignment to your GitHub account by clicking through the assignment folder till you reach just the "Counter" folder, Click "fork".

2. Copy the URL in the field above the "clone button":
![screen shot 2015-06-12 at 12 28 58 am](https://cloud.githubusercontent.com/assets/6679175/8123590/714bfd72-109a-11e5-9a9a-7f90bff87014.png)


2. When Xcode launches, it presents the Welcome Screen. Select "Check out existing project":
![screen shot 2015-06-12 at 12 18 59 am](https://cloud.githubusercontent.com/assets/6679175/8123550/942247da-1099-11e5-983f-13a369d92137.png)

3. Paste the URL into the "Or enter a repository location" field:
![screen shot 2015-06-12 at 12 19 49 am](https://cloud.githubusercontent.com/assets/6679175/8123624/32ad4d90-109b-11e5-834c-f265107b5c6d.png)

4. Save to the location of your local Git repository on your hard drive:
![screen shot 2015-06-12 at 12 20 05 am](https://cloud.githubusercontent.com/assets/6679175/8123616/119b07fa-109b-11e5-8e2f-be42bd623c2f.png)

**Comment by jcgohlke** [comment]
Very good. Please review and close this issue.

**Comment by KevinSFC** [comment]
Thanks!
