### ISSUE TITLE
00 -- This is Heavy -- Eli Correa

### ISSUE THREAD

**Issue by EliCorrea** [TheIronYard--Orlando/2015--SUMMER--iOS#7]
# 00 -- This is Heavy

![BTTF](http://i.giphy.com/KL6leJilrOEVi.gif)

Most of this assignment is getting your laptop ready for Day 1 by installing a few key pieces of software and registering for certain invaluable services like Github and Slack. Beyond that, you'll start to get familiar with Github and basic source control concepts that we'll be using throughout the class. These aren't specific to any language or toolkit; they're universal developer skills.

## Requirements

Click on this file in Github and use the __Raw__ button to see the unrendered Markdown text. If you copy and paste the text _as is_ from the __Tasks__ and __Deliverables__ sections below into the __Description__ of your issue, you should end up with a bunch of checkboxes, just like these, thanks to [the way that Github interprets Markdown](https://guides.github.com/features/mastering-markdown/). As you complete tasks, check off the corresponding checkboxes and let your progress bar fill! Read [Mastering Issues](https://guides.github.com/features/issues/) for more information on creating issues in Github.

### Tasks:

* [X] [Create a Github account](https://github.com/signup)
* [X] Find and star [the class project](https://github.com/TheIronYard--Orlando/2015--SUMMER--iOS)
* [x] Read [the Home page on the class wiki](https://github.com/TheIronYard--Orlando/2015--SUMMER--iOS/wiki)
* [x] [Create a new _WIP Issue_](https://github.com/TheIronYard--Orlando/2015--SUMMER--iOS/issues/new)
  * [x] Named `00 -- This is Heavy -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  * [x] With this checklist as the description
* [x] [Edit your Github profile](https://github.com/settings/profile) to provide:
  * [x] A picture, so I can recognize your face.
  * [x] Your full name, so I can recognize your name.
  * [x] A valid public email address, so I can contact you if I need to.
* [x] [Complete the "Hello World" Github guide](https://guides.github.com/activities/hello-world/)
  * [x] Add a link to your new Github repo as a comment on your *WIP Issue*
* [x] Create a new repository called `TIY-Assignments`
  * [x] Check the box to create an initial `README.md` file
  * [x] Select the `CC0` -- "Creative Commons" license for your work
  * [x] Add a link to your `TIY-Assignments` repo as a comment on your *WIP Issue*
* [ ] [Complete the "Forking Projects" Github guide](https://guides.github.com/activities/forking/)
    * [ ] Add a link to your `Fork-and-Spoon` repo as a comment on your *WIP Issue*
* [x] Install Xcode from the Mac App Store. Simply search for _Xcode_.
* [x] Open Xcode. Click the _Xcode_ menu in the menubar, then choose _Preferences_. Navigate to the _Downloads_ tab and install the latest iOS documentation (currently iOS 8.3). Once fully downloaded, the docset should have a small checkmark next to it.
* [x] Install Dash from the Mac App Store. Navigate to the Dash app's preferences and choose the _Downloads_ tab. Install the following docsets:
    * [x] iOS 8.3 (or latest, it will find the already loaded set from the step above)
    * [x] Swift 1.2 (or latest)
    * [x] Objective-C
    * [x] Objective-C Blocks
    * [x] Xcode
    * [x] iOS Design
    * [x] Take a screenshot of the _Docsets_ tab in preferences and attach it to your _WIP Issue_
* [ ] Watch _The Long Run_ Videos on [Delve.tv](http://delve.tv)
   * [ ] [_The Long Game_, part 1](http://delve.tv/the-long-game-part-one/)
   * [ ] [_The Long Game_, part 2](http://delve.tv/the-long-game-part-2/)
* [ ] Look at the Prework-A file for instructions on how to complete the Counter app.

### Deliverables:

* [x] _WIP Issue_
  * [x] named `00 -- This is Heavy -- YOUR NAME`
  * [ ] with description matching __Tasks__
* [x] A Github Profile with:
  * [x] Intelligible picture of yourself
  * [x] Your full name
  * [x] A valid email address
* [x] Comments on your *WIP Issue* with links to your repos for
  * [x] `Hello-World`
  * [x] `TIY-Assignments`
  * [ ] `Fork-and-Spoon`
  * [x] Attached image from the Dash preference pane for installed docsets
* [ ] A completed Counter app project, added to your TIYAssignments repo

## Extracurricular Activities

Regardless of how good you think you are at typing, a lot of the mistakes you make at first will be simple typographic errors. If you _don't_ know how to touch type (i.e. without looking at the keyboard), start practicing _now_ with http://www.keybr.com/. If you're fairly confident in your typing ability, try working through the Objective-C lessons on http://typing.io

If you've finished everything above and are still looking for more, work through these intro tutorials on the C and Objective-C languages. Objective-C is called a "superset" of ANSI C, meaning that it provides full backwards compatibility with C, and extends it in several important areas. The following tutorials will give you an introduction to several concepts we will use quite heavily in class:

* [Learning C: A Primer](http://code.tutsplus.com/tutorials/learning-c-a-primer--mobile-13916)
* [Getting Started with Objective-C](http://code.tutsplus.com/tutorials/getting-started-with-objective-c--mobile-13944)

**Comment by EliCorrea** [comment]
https://github.com/EliCorrea/TIY-Assignments.git

**Comment by EliCorrea** [comment]
https://github.com/EliCorrea/hello-world.git

**Comment by EliCorrea** [comment]
![docset](https://cloud.githubusercontent.com/assets/12883824/8222105/c5db11b8-1534-11e5-83d9-e170f268a7d9.jpg)

**Comment by EliCorrea** [comment]
Xcode Preference View

![xcode preference view](https://cloud.githubusercontent.com/assets/12883824/8222200/d37dab18-1535-11e5-9077-f4755451b3cb.jpg)

**Comment by jcgohlke** [comment]
Good job. Please review and close.
